const SONGS = {
  Pop: [
    {title:'Blinding Lights',artist:'The Weeknd'},
    {title:'As It Was',artist:'Harry Styles'},
    {title:'Stay',artist:'The Kid LAROI'},
    {title:'Levitating',artist:'Dua Lipa'},
    {title:'good 4 u',artist:'Olivia Rodrigo'},
    {title:'Watermelon Sugar',artist:'Harry Styles'},
    {title:'Peaches',artist:'Justin Bieber'},
    {title:'drivers license',artist:'Olivia Rodrigo'},
    {title:'Montero',artist:'Lil Nas X'},
    {title:'Save Your Tears',artist:'The Weeknd'},
    {title:'Butter',artist:'BTS'},
    {title:'Heat Waves',artist:'Glass Animals'},
    {title:'Industry Baby',artist:'Lil Nas X'},
    {title:'Easy On Me',artist:'Adele'},
    {title:'Bad Habits',artist:'Ed Sheeran'},
    {title:'Anti-Hero',artist:'Taylor Swift'},
    {title:'Flowers',artist:'Miley Cyrus'},
    {title:'Cruel Summer',artist:'Taylor Swift'},
    {title:'Unholy',artist:'Sam Smith'},
    {title:'About Damn Time',artist:'Lizzo'},
    {title:'Calm Down',artist:'Rema'},
    {title:'Escapism',artist:'RAYE'},
    {title:'Shivers',artist:'Ed Sheeran'},
    {title:'Die For You',artist:'The Weeknd'},
    {title:'Shape of You',artist:'Ed Sheeran'},
    {title:'Someone You Loved',artist:'Lewis Capaldi'},
    {title:'Dance Monkey',artist:'Tones and I'},
    {title:'Dynamite',artist:'BTS'},
    {title:'Permission to Dance',artist:'BTS'},
    {title:'Happier',artist:'Olivia Rodrigo'},
    {title:'traitor',artist:'Olivia Rodrigo'},
    {title:'Positions',artist:'Ariana Grande'},
    {title:'34+35',artist:'Ariana Grande'},
    {title:'Love Story',artist:'Taylor Swift'},
    {title:'Shake It Off',artist:'Taylor Swift'},
    {title:'New Rules',artist:'Dua Lipa'},
    {title:'Dont Start Now',artist:'Dua Lipa'},
    {title:'Physical',artist:'Dua Lipa'},
    {title:'Midnight Rain',artist:'Taylor Swift'},
    {title:'Bejeweled',artist:'Taylor Swift'},
    {title:'Lavender Haze',artist:'Taylor Swift'},
    {title:'Karma',artist:'Taylor Swift'},
    {title:'Flowers',artist:'Miley Cyrus'},
    {title:'Prisoner',artist:'Miley Cyrus'},
    {title:'Wrecking Ball',artist:'Miley Cyrus'},
    {title:'Ghost Town',artist:'Adam Lambert'},
    {title:'Stay With Me',artist:'Sam Smith'},
    {title:'Writing on the Wall',artist:'Sam Smith'},
    {title:'Lose You to Love Me',artist:'Selena Gomez'},
    {title:'Rare',artist:'Selena Gomez'},
  ],
  'Hip-Hop': [
    {title:'God Did',artist:'DJ Khaled'},
    {title:'Rich Flex',artist:'Drake'},
    {title:'Knife Talk',artist:'Drake'},
    {title:'Way 2 Sexy',artist:'Drake'},
    {title:'Pushin P',artist:'Gunna'},
    {title:'Family Ties',artist:'Baby Keem'},
    {title:'Big Energy',artist:'Latto'},
    {title:'Gorgeous',artist:'Tyler the Creator'},
    {title:'Essence',artist:'Wizkid'},
    {title:'Rapstar',artist:'Polo G'},
    {title:'We Paid',artist:'Lil Baby'},
    {title:'Thot Shit',artist:'Megan Thee Stallion'},
    {title:'Streets',artist:'Doja Cat'},
    {title:'First Class',artist:'Jack Harlow'},
    {title:'Nail Tech',artist:'Jack Harlow'},
    {title:'Magnolia',artist:'Playboi Carti'},
    {title:'Praise God',artist:'Kanye West'},
    {title:'Bath Salts',artist:'ASAP Mob'},
    {title:'Back In Blood',artist:'Pooh Shiesty'},
    {title:'Tiptoe',artist:'Gunna'},
    {title:'Betrayal',artist:'Trippie Redd'},
    {title:'Astronaut In The Ocean',artist:'Masked Wolf'},
    {title:'Heat',artist:'Future'},
    {title:'Smokin Out the Window',artist:'Silk Sonic'},
    {title:'We Cry Together',artist:'Kendrick Lamar'},
    {title:'N95',artist:'Kendrick Lamar'},
    {title:'Father Time',artist:'Kendrick Lamar'},
    {title:'Jhene',artist:'Future'},
    {title:'Wait for U',artist:'Future'},
    {title:'Jimmy Cooks',artist:'Drake'},
    {title:'Champagne Poetry',artist:'Drake'},
    {title:'Girls Want Girls',artist:'Drake'},
    {title:'TSU',artist:'Tyler the Creator'},
    {title:'Lumberjack',artist:'Tyler the Creator'},
    {title:'Juggernaut',artist:'Tyler the Creator'},
    {title:'Come On',artist:'Lil Baby'},
    {title:'Forever',artist:'Lil Baby'},
    {title:'Sum 2 Prove',artist:'Lil Baby'},
    {title:'Millions',artist:'Polo G'},
    {title:'Pop Out',artist:'Polo G'},
    {title:'Hall of Fame',artist:'Polo G'},
    {title:'Kiss Me More',artist:'Doja Cat'},
    {title:'Need to Know',artist:'Doja Cat'},
    {title:'Woman',artist:'Doja Cat'},
    {title:'Try It On',artist:'Megan Thee Stallion'},
    {title:'Body',artist:'Megan Thee Stallion'},
    {title:'Sweetest Pie',artist:'Megan Thee Stallion'},
    {title:'What I Want',artist:'Latto'},
    {title:'777',artist:'Latto'},
    {title:'Sunshine',artist:'Lil Durk'},
  ],
  Rock: [
    {title:'Beggin',artist:'Maneskin'},
    {title:'Enemy',artist:'Imagine Dragons'},
    {title:'Mr. Brightside',artist:'The Killers'},
    {title:'Boulevard of Broken Dreams',artist:'Green Day'},
    {title:'Smells Like Teen Spirit',artist:'Nirvana'},
    {title:'Seven Nation Army',artist:'White Stripes'},
    {title:'Bohemian Rhapsody',artist:'Queen'},
    {title:'Thunderstruck',artist:'AC/DC'},
    {title:'Welcome to the Black Parade',artist:'My Chemical Romance'},
    {title:'Numb',artist:'Linkin Park'},
    {title:'In the End',artist:'Linkin Park'},
    {title:'Paradise City',artist:'Guns N Roses'},
    {title:'Sweet Child O Mine',artist:'Guns N Roses'},
    {title:'Dont Stop Believin',artist:'Journey'},
    {title:'Eye of the Tiger',artist:'Survivor'},
    {title:'Livin on a Prayer',artist:'Bon Jovi'},
    {title:'Jump',artist:'Van Halen'},
    {title:'Everlong',artist:'Foo Fighters'},
    {title:'Best of You',artist:'Foo Fighters'},
    {title:'Float On',artist:'Modest Mouse'},
    {title:'Take Me Out',artist:'Franz Ferdinand'},
    {title:'Helena',artist:'My Chemical Romance'},
    {title:'Sugar Were Goin Down',artist:'Fall Out Boy'},
    {title:'Dance Dance',artist:'Fall Out Boy'},
    {title:'Should I Stay or Should I Go',artist:'The Clash'},
    {title:'Basket Case',artist:'Green Day'},
    {title:'American Idiot',artist:'Green Day'},
    {title:'Holiday',artist:'Green Day'},
    {title:'Creep',artist:'Radiohead'},
    {title:'Karma Police',artist:'Radiohead'},
    {title:'Fake Plastic Trees',artist:'Radiohead'},
    {title:'Come As You Are',artist:'Nirvana'},
    {title:'Lithium',artist:'Nirvana'},
    {title:'Heart Shaped Box',artist:'Nirvana'},
    {title:'Photograph',artist:'Nickelback'},
    {title:'How You Remind Me',artist:'Nickelback'},
    {title:'Rockstar',artist:'Nickelback'},
    {title:'Under the Bridge',artist:'Red Hot Chili Peppers'},
    {title:'Californication',artist:'Red Hot Chili Peppers'},
    {title:'Cant Stop',artist:'Red Hot Chili Peppers'},
    {title:'Yellow',artist:'Coldplay'},
    {title:'The Scientist',artist:'Coldplay'},
    {title:'Fix You',artist:'Coldplay'},
    {title:'Clocks',artist:'Coldplay'},
    {title:'Speed of Sound',artist:'Coldplay'},
    {title:'Somebody Told Me',artist:'The Killers'},
    {title:'Human',artist:'The Killers'},
    {title:'Radioactive',artist:'Imagine Dragons'},
    {title:'Demons',artist:'Imagine Dragons'},
    {title:'Thunder',artist:'Imagine Dragons'},
  ],
  'R&B': [
    {title:'Leave the Door Open',artist:'Silk Sonic'},
    {title:'Smokin Out the Window',artist:'Silk Sonic'},
    {title:'Essence',artist:'Wizkid'},
    {title:'Pick Up Your Feelings',artist:'Jazmine Sullivan'},
    {title:'Best Part',artist:'Daniel Caesar'},
    {title:'Nights',artist:'Frank Ocean'},
    {title:'Ivy',artist:'Frank Ocean'},
    {title:'Come Through',artist:'HER'},
    {title:'Virgos Groove',artist:'Beyonce'},
    {title:'Cuff It',artist:'Beyonce'},
    {title:'Break My Soul',artist:'Beyonce'},
    {title:'Die For You',artist:'The Weeknd'},
    {title:'Earned It',artist:'The Weeknd'},
    {title:'Often',artist:'The Weeknd'},
    {title:'Good Days',artist:'SZA'},
    {title:'I Hate U',artist:'SZA'},
    {title:'Saturn',artist:'SZA'},
    {title:'Shirt',artist:'SZA'},
    {title:'Snooze',artist:'SZA'},
    {title:'Kill Bill',artist:'SZA'},
    {title:'Nobody',artist:'Tems'},
    {title:'Free Mind',artist:'Tems'},
    {title:'Climax',artist:'Usher'},
    {title:'Loved By You',artist:'Lucky Daye'},
    {title:'Crazy in Love',artist:'Beyonce'},
    {title:'Lemonade',artist:'Beyonce'},
    {title:'Hold Up',artist:'Beyonce'},
    {title:'Formation',artist:'Beyonce'},
    {title:'Telephone',artist:'Lady Gaga'},
    {title:'Stay With Me',artist:'Sam Smith'},
    {title:'Superstar',artist:'Usher'},
    {title:'Yeah',artist:'Usher'},
    {title:'Confessions Part II',artist:'Usher'},
    {title:'Burn',artist:'Usher'},
    {title:'Get to You',artist:'Lucky Daye'},
    {title:'Over',artist:'Lucky Daye'},
    {title:'From Zero to Love',artist:'Jazmine Sullivan'},
    {title:'Lost One',artist:'Jazmine Sullivan'},
    {title:'Need U Bad',artist:'Jazmine Sullivan'},
    {title:'Best of Me',artist:'Daniel Caesar'},
    {title:'Japanese Denim',artist:'Daniel Caesar'},
    {title:'Always',artist:'Daniel Caesar'},
    {title:'Pilot Jones',artist:'Frank Ocean'},
    {title:'Thinkin Bout You',artist:'Frank Ocean'},
    {title:'Sweet Life',artist:'Frank Ocean'},
    {title:'Garden',artist:'HER'},
    {title:'Focus',artist:'HER'},
    {title:'I Used to Know Her',artist:'HER'},
    {title:'Damage',artist:'HER'},
    {title:'Find a Way',artist:'Tems'},
  ],
  Country: [
    {title:'Fancy Like',artist:'Walker Hayes'},
    {title:'10000 Hours',artist:'Dan + Shay'},
    {title:'Sand In My Boots',artist:'Morgan Wallen'},
    {title:'Wasted on You',artist:'Morgan Wallen'},
    {title:'Whiskey Glasses',artist:'Morgan Wallen'},
    {title:'Dangerous',artist:'Morgan Wallen'},
    {title:'More Than My Hometown',artist:'Morgan Wallen'},
    {title:'Buy Dirt',artist:'Jordan Davis'},
    {title:'Better Together',artist:'Luke Combs'},
    {title:'Cold as You',artist:'Luke Combs'},
    {title:'Forever After All',artist:'Luke Combs'},
    {title:'Beer Never Broke My Heart',artist:'Luke Combs'},
    {title:'Hell of a View',artist:'Eric Church'},
    {title:'Starting Over',artist:'Chris Stapleton'},
    {title:'Tennessee Whiskey',artist:'Chris Stapleton'},
    {title:'Humble and Kind',artist:'Tim McGraw'},
    {title:'Famous Friends',artist:'Chris Young'},
    {title:'One Margarita',artist:'Luke Bryan'},
    {title:'Beers on Me',artist:'Dierks Bentley'},
    {title:'Half of My Hometown',artist:'Kelsea Ballerini'},
    {title:'Girl Goin Nowhere',artist:'Ashley McBryde'},
    {title:'Better Boat',artist:'Kenny Chesney'},
    {title:'Heartless',artist:'Diplo'},
    {title:'5 Foot 9',artist:'Eric Church'},
    {title:'6 Feet',artist:'Thomas Rhett'},
    {title:'What Your Country Song',artist:'Thomas Rhett'},
    {title:'Meant to Be',artist:'Bebe Rexha'},
    {title:'Body Like a Back Road',artist:'Sam Hunt'},
    {title:'Take Your Time',artist:'Sam Hunt'},
    {title:'House Party',artist:'Sam Hunt'},
    {title:'When the Party is Over',artist:'Jordan Davis'},
    {title:'Singles You Up',artist:'Jordan Davis'},
    {title:'Slow Dance in a Parking Lot',artist:'Jordan Davis'},
    {title:'Up Down',artist:'Morgan Wallen'},
    {title:'Chasin You',artist:'Morgan Wallen'},
    {title:'Cover Me Up',artist:'Morgan Wallen'},
    {title:'Beautiful Crazy',artist:'Luke Combs'},
    {title:'Even Though Im Leaving',artist:'Luke Combs'},
    {title:'When It Rains It Pours',artist:'Luke Combs'},
    {title:'Does to Me',artist:'Luke Combs'},
    {title:'Small Town Small',artist:'Chris Young'},
    {title:'Raised on Country',artist:'Chris Young'},
    {title:'Gettin You Home',artist:'Chris Young'},
    {title:'Knockin Boots',artist:'Luke Bryan'},
    {title:'Country Girl',artist:'Luke Bryan'},
    {title:'Play It Again',artist:'Luke Bryan'},
    {title:'Somewhere on a Beach',artist:'Dierks Bentley'},
    {title:'Drunk on a Plane',artist:'Dierks Bentley'},
    {title:'Different for Girls',artist:'Dierks Bentley'},
    {title:'uiowa',artist:'Walker Hayes'},
  ],
  Electronic: [
    {title:'One More Time',artist:'Daft Punk'},
    {title:'Around the World',artist:'Daft Punk'},
    {title:'Get Lucky',artist:'Daft Punk'},
    {title:'Strobe',artist:'deadmau5'},
    {title:'Scary Monsters and Nice Sprites',artist:'Skrillex'},
    {title:'Bangarang',artist:'Skrillex'},
    {title:'Animals',artist:'Martin Garrix'},
    {title:'Lean On',artist:'Major Lazer'},
    {title:'Levels',artist:'Avicii'},
    {title:'Wake Me Up',artist:'Avicii'},
    {title:'Dont You Worry Child',artist:'Swedish House Mafia'},
    {title:'Silence',artist:'Marshmello'},
    {title:'Alone',artist:'Marshmello'},
    {title:'Faded',artist:'Alan Walker'},
    {title:'Darkside',artist:'Alan Walker'},
    {title:'Titanium',artist:'David Guetta'},
    {title:'Without You',artist:'David Guetta'},
    {title:'Happier',artist:'Marshmello'},
    {title:'Friends',artist:'Marshmello'},
    {title:'Head and Heart',artist:'Joel Corry'},
    {title:'Feel So Close',artist:'Calvin Harris'},
    {title:'Summer',artist:'Calvin Harris'},
    {title:'This Is What You Came For',artist:'Calvin Harris'},
    {title:'One Kiss',artist:'Calvin Harris'},
    {title:'Promises',artist:'Calvin Harris'},
    {title:'Hey Now',artist:'London Grammar'},
    {title:'Stay the Night',artist:'Zedd'},
    {title:'Beautiful Now',artist:'Zedd'},
    {title:'The Middle',artist:'Zedd'},
    {title:'Clarity',artist:'Zedd'},
    {title:'Spectrum',artist:'Zedd'},
    {title:'Tremor',artist:'Dimitri Vegas'},
    {title:'In the Name of Love',artist:'Martin Garrix'},
    {title:'Scared to Be Lonely',artist:'Martin Garrix'},
    {title:'High on Life',artist:'Martin Garrix'},
    {title:'Waiting for Love',artist:'Avicii'},
    {title:'Hey Brother',artist:'Avicii'},
    {title:'The Nights',artist:'Avicii'},
    {title:'Without Me',artist:'Avicii'},
    {title:'Broken Arrows',artist:'Avicii'},
    {title:'Reload',artist:'Sebastian Ingrosso'},
    {title:'Save the World',artist:'Swedish House Mafia'},
    {title:'Greyhound',artist:'Swedish House Mafia'},
    {title:'Until One',artist:'Swedish House Mafia'},
    {title:'Clap Your Hands',artist:'deadmau5'},
    {title:'Professional Griefers',artist:'deadmau5'},
    {title:'Ghost n Stuff',artist:'deadmau5'},
    {title:'Raise Your Weapon',artist:'deadmau5'},
    {title:'Ghosts n Stuff',artist:'deadmau5'},
    {title:'Superstar',artist:'Peggy Gou'},
  ],
};

const ARTISTS = {
  Pop: [
    'Taylor Swift','Ed Sheeran','Adele','Harry Styles','Dua Lipa',
    'Olivia Rodrigo','Justin Bieber','Ariana Grande','Billie Eilish','The Weeknd',
    'Selena Gomez','Sam Smith','Lizzo','Miley Cyrus','BTS',
    'Shawn Mendes','Camila Cabello','Charlie Puth','Halsey','Post Malone',
    'Lady Gaga','Katy Perry','Bruno Mars','Cardi B','Nicki Minaj',
    'Bebe Rexha','Meghan Trainor','Anne-Marie','Ava Max','Lewis Capaldi',
    'Conan Gray','Surfaces','Tones and I','Lorde','Lana Del Rey',
    'Demi Lovato','Nick Jonas','Jonas Brothers','One Direction','5SOS',
    'Niall Horan','Zayn','Louis Tomlinson','Liam Payne','Panic at the Disco',
    'Imagine Dragons','Coldplay','Maroon 5','OneRepublic','Matchbox Twenty',
  ],
  'Hip-Hop': [
    'Drake','Kendrick Lamar','J. Cole','Travis Scott','Lil Baby',
    'Gunna','Future','21 Savage','Post Malone','Cardi B',
    'Nicki Minaj','Megan Thee Stallion','Doja Cat','Jack Harlow','Tyler the Creator',
    'ASAP Rocky','Playboi Carti','Lil Uzi Vert','Polo G','Roddy Ricch',
    'YNW Melly','NBA YoungBoy','DaBaby','Lil Durk','Moneybagg Yo',
    'Lil Tjay','Myke Towers','Sech','Bad Bunny','Ozuna',
    'Chance the Rapper','Big Sean','2 Chainz','Meek Mill','Rick Ross',
    'Wiz Khalifa','Mac Miller','Logic','NF','Eminem',
    'Jay-Z','Kanye West','Nas','Lil Wayne','Nelly',
    'Snoop Dogg','Ice Cube','DMX','Ludacris','T.I.',
  ],
  Rock: [
    'Foo Fighters','Green Day','Nirvana','Linkin Park','My Chemical Romance',
    'Fall Out Boy','Paramore','Panic at the Disco','Twenty One Pilots','Imagine Dragons',
    'The Killers','Arctic Monkeys','Radiohead','Coldplay','Muse',
    'Red Hot Chili Peppers','Pearl Jam','Soundgarden','Alice in Chains','Stone Temple Pilots',
    'Metallica','Guns N Roses','AC/DC','Aerosmith','Van Halen',
    'Led Zeppelin','Black Sabbath','Ozzy Osbourne','Iron Maiden','Judas Priest',
    'The Beatles','The Rolling Stones','The Who','The Doors','Pink Floyd',
    'David Bowie','Queen','Elton John','Fleetwood Mac','Eagles',
    'Bon Jovi','Def Leppard','Poison','Warrant','Whitesnake',
    'Nickelback','Creed','Puddle of Mudd','3 Doors Down','Staind',
  ],
  'R&B': [
    'Beyonce','SZA','The Weeknd','Frank Ocean','Tems',
    'HER','Daniel Caesar','Silk Sonic','Bruno Mars','Anderson Paak',
    'Usher','Alicia Keys','John Legend','Mary J Blige','Erykah Badu',
    'Lauryn Hill','Jazmine Sullivan','Lucky Daye','Summer Walker','Giveon',
    'Brent Faiyaz','DVSN','H.E.R.','Jhene Aiko','Kehlani',
    'Ella Mai','Ari Lennox','Snoh Aalegra','Lucky Daye','Moonchild',
    'Musiq Soulchild','Ne-Yo','R. Kelly','Tank','Ginuwine',
    'Mario','Lloyd','Omarion','B2K','Pretty Ricky',
    'Chris Brown','Trey Songz','Miguel','Bryson Tiller','PartyNextDoor',
    'Drake','Roy Woods','Majid Jordan','dvsn','NAV',
  ],
  Country: [
    'Morgan Wallen','Luke Combs','Chris Stapleton','Eric Church','Blake Shelton',
    'Luke Bryan','Tim McGraw','Kenny Chesney','Dierks Bentley','Jason Aldean',
    'Thomas Rhett','Sam Hunt','Jordan Davis','Walker Hayes','Kelsea Ballerini',
    'Carrie Underwood','Miranda Lambert','Maren Morris','Kacey Musgraves','Ashley McBryde',
    'Chris Young','Brett Eldredge','Dan + Shay','Florida Georgia Line','Old Dominion',
    'Zac Brown Band','Brothers Osborne','Midland','Turnpike Troubadours','Tyler Childers',
    'Cody Johnson','Sturgill Simpson','Colter Wall','Charley Crockett','Orville Peck',
    'Brandi Carlile','Phoebe Bridgers','Gillian Welch','Emmylou Harris','Dolly Parton',
    'Willie Nelson','Waylon Jennings','Johnny Cash','Merle Haggard','George Strait',
    'Alan Jackson','Garth Brooks','Reba McEntire','Shania Twain','Faith Hill',
  ],
  Electronic: [
    'Daft Punk','Avicii','Calvin Harris','Martin Garrix','Zedd',
    'Marshmello','Alan Walker','Skrillex','deadmau5','Swedish House Mafia',
    'David Guetta','Tiesto','Kygo','Diplo','Major Lazer',
    'The Chainsmokers','Illenium','Odesza','Flume','Madeon',
    'Porter Robinson','Rezz','Virtual Self','Aphex Twin','Boards of Canada',
    'Four Tet','Jon Hopkins','Nicolas Jaar','Jamie xx','Mount Kimbie',
    'Bicep','Peggy Gou','DJ Koze','Ben UFO','Objekt',
    'Paul Kalkbrenner','Richie Hawtin','Carl Cox','Sven Vath','Nina Kraviz',
    'Charlotte de Witte','Amelie Lens','Joseph Capriati','Adam Beyer','Drumcode',
    'Eric Prydz','Axwell','Sebastian Ingrosso','Steve Angello','Knife Party',
  ],
};

function getSongPool(genre) { return SONGS[genre] || []; }
function getArtistPool(genre) { return (ARTISTS[genre] || []).map(name => ({ name })); }
function getGenres() { return Object.keys(SONGS); }

module.exports = { SONGS, ARTISTS, getSongPool, getArtistPool, getGenres };
